### ISSUE TITLE
Add support for Open API 3.0

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/schemathesis#10]
A notable different is "requestBody" instead of `in=body`

also: `in=cookie`

**Comment by sobolevn** [comment]
Sorry, this is not clear from the docs: is v3 of OpenAPI is supported?

**Comment by sobolevn** [comment]
Related issue from `swagger-conformance`: https://github.com/olipratt/swagger-conformance/issues/9

**Comment by Stranger6667** [comment]
Hello! Yes, it is supported

**Comment by sobolevn** [comment]
Nice! It would be awesome to update docs about versions you support!

**Comment by Stranger6667** [comment]
Done :)

**Comment by Stranger6667** [comment]
Thank you for asking :)
