### ISSUE TITLE
Display progress during the CLI run

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/schemathesis#125]
To show that the app is not stuck it would be very nice to show some progress during the run.

We can show the current endpoint/method and number of executed tests

It could look like this:

```
GET:    /v1/users .......
POST:   /v1/users ...
```
And show the number of tests with dots (pytest style), maybe we can also show failures with "F", not sure.

To implement it we should not capture all stdout during `runner.execute` (`cli.__init:79`), but only hypothesis one + write the progress on each iteration of execution.

Maybe it will be easier to change `runner.execute_from_schema` into a generator so the runner itself will not know about another part that will write progress info to the terminal - I'd like to avoid adding this logic into the runner itself since it is relevant more to the CLI part.

Actually, if the control will be yielded upper from the runner, then that part could use `StatsCollector` to write the progress - this might need some restructuring in the runner. 

Something like this:
```
# cli/__init__.py
stats = StatsCollector()
for _ in runner.execute(..., stats):
    click.echo("some info from stats/runner")
```

Also if the runner will have an internal state, then it will be easier to report the current/next test.

On the other hand, the runner should be still easy to use, converting it to a generator shouldn't change the current API

**Comment by brennerm** [comment]
Do you have some application and tests that one could use for developing this?

**Comment by Stranger6667** [comment]
Hello @brennerm :)
We have an app in the test suite, that could be extended for this purpose, but this is definitely something we can improve to simplify development.
Usually, I run one of our internal apps and execute `schemathesis` against it.

**Comment by Stranger6667** [comment]
It is here - https://github.com/kiwicom/schemathesis/blob/master/test/test_runner.py#L15 and it is run in a separate thread. I am going to work on the issues description and dev environment soon, so it will be easier to start :)

**Comment by Stranger6667** [comment]
I added a development server with few endpoints for convenient local development:
https://github.com/kiwicom/schemathesis#local-development
