### ISSUE TITLE
@settings(max_examples=5) but it executed for 10 times

### ISSUE THREAD

**Issue by balzaron** [kiwicom/schemathesis#198]
@settings(max_examples=5) cannot refrain the example times.
i fulfilled the max_examples = 5 but it execute 10 times.

**Comment by Stranger6667** [comment]
Hello @balzaron !

Could you, please, provide information about your schemathesis, hypothesis and Python versions? Also some minimal reproducible example will be great to have if possible. Please note, that max_examples are applied per endpoint, e.g if you have 2 endpoints and max_examples=5, then you could have maximum 10 examples in total, however it could be fewer examples if some endpoint accepts nothing or some static data - there is not much to generate. Also, if tests are failing, then hypothesis tries to find some minimal example to reproduce the failure - these examples are not counted towards max_examples setting AFAIK

**Comment by balzaron** [comment]
Hi @Stranger6667 
![image](https://user-images.githubusercontent.com/9757578/67913463-212ae100-fbc8-11e9-89db-899ca6035a3b.png)

my code is as below
```
@schema.parametrize()
@settings(deadline=900, max_examples=1)
def test_no_server_errors(case:Case):
    path = case.path
    print(path)
    assert False
```
----------------------------- Captured stdout call -----------------------------
/api/data-gate/get-security-by-asset-ids
/api/data-gate/get-security-by-asset-ids
/api/data-gate/get-security-by-asset-ids
---------------------------------- Hypothesis ----------------------------------
and you can see that this case executed at least for 3 times.
i am sure i only have 1 endpoint in my swagger yaml file because i comment other endpoints just for a test.
And your project is excellent! it is really helpful!

**Comment by balzaron** [comment]
Hi @Stranger6667 
thx for your reply
![image](https://user-images.githubusercontent.com/9757578/67914037-ef1a7e80-fbc9-11e9-9b13-1354898112a1.png)
```
@schema.parametrize()
@settings(deadline=900, max_examples=1)
def test_no_server_errors(case:Case):
    path = case.path
    print(path)
    assert False
```
and it output 
```
AssertionError
----------------------------- Captured stdout call -----------------------------
/api/data-gate/get-security-by-asset-ids
/api/data-gate/get-security-by-asset-ids
/api/data-gate/get-security-by-asset-ids
---------------------------------- Hypothesis ----------------------------------
```
you can see this case executed 3 times. and i am sure i have commented all the other endpoints in my swagger yaml file for this test.

appreciate for your project it is really helpful.

**Comment by Stranger6667** [comment]
I am very pleased to hear that the library is helpful for you :)

Hypothesis re-runs failures to ensure, that they are reproducible and are not caused by some sort of randomness, here is the code for it - https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/core.py#L683

If an example failed on the first run and passed on the second, then Hypothesis will raise an error:

```
Unreliable assumption: An example which satisfied assumptions on the first run now fails it.
```

or:

```
Hypothesis found %d distinct failures, but %d of them exhibited some sort of flaky behaviour.
```

However, it might be not that straightforward and visible from the Schemathesis side, maybe we can categorize such runs in a separate group in the summary to make them more identifiable + update documentation on this topic. What do you think?

**Comment by balzaron** [comment]
Yes, i got it. i will close this issue
