### ISSUE TITLE
Support for "cookie" parameter in OAS3

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/schemathesis#21]
Implementation could include these steps:
- Adding a condition branch in `schemas.OpenApi30.process_parameter` for `cookie` type
- Adding a corresponding method for handling this parameter type - there is nothing specific, and it could be similar to `process_query`
- Extend `PreparedParameters`, `Endpoint`, `Case` classes with `cookies` attribute of `Dict[str, Any]` type.
- Extend `generator.PARAMETERS` and `generator.get_case_strategy` accordingly (it should be similar to other parameters)

**Comment by paveldedik** [comment]
Shouldn't this be supported only by `OpenApi30`? I couldn't find `cookie` parameters in swagger 2.0 specification.

**Comment by Stranger6667** [comment]
yep, it is OAS3 only

**Comment by paveldedik** [comment]
Ok, why are you suggesting modifying `schemas.SwaggerV20.process_parameter` then? It should be `schemas.OpenApi30.process_parameter`, it is just typo right?

**Comment by Stranger6667** [comment]
oh, I didn't spot it, you are right

**Comment by Stranger6667** [comment]
Fixed

**Comment by paveldedik** [comment]
OK, thank you, just wanted to make sure :-)
