### ISSUE TITLE
loosen importlib metadata pin

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [kiwicom/schemathesis#314]
https://github.com/kiwicom/schemathesis/blob/3542d91d2e7402235e7b2dc995ed7017a0265ff6/pyproject.toml#L37

while pulling in schemathesis
 as a new dependency(cause it does great things) we noted a conflict

`pkg_resources.ContextualVersionConflict: (importlib-metadata 1.1.0 (/var/lib/jenkins/workspace/$REDACTED/py-venv/lib/python3.6/site-packages), Requirement.parse('importlib_metadata<0.24.0,>=0.23.0'), {'schemathesis'})`

i believe it should e relatively safe to unpin or at least switch to the 1.x series

**Comment by RonnyPfannschmidt** [comment]
i'm happy to provide a pr updating the pin to `^1.0`

**Comment by Stranger6667** [comment]
Hello Ronny!

Thanks! Yep, I'd be happy to merge that PR :)
