### ISSUE TITLE
How I can disable some checks?

### ISSUE THREAD

**Issue by MissiaL** [kiwicom/schemathesis#321]
Sometimes my tests fail when special characters are passed to parameters, such as `\ud8dd`
I would like to disable checks of this type

**Comment by Stranger6667** [comment]
Hej @MissiaL !

I think this one could be solved via #313  and might look like this (or with proper traversal of keys & values):

```
def filter_chars(strategy):
    return strategy.filter(lambda value: "\ud8dd" not in str(value))

schemathesis.hooks.strategies.register("body", filter_chars)
```

However, it will be slower than it could be.

There are no hooks from `hypothesis-jsonschema` at the moment, but in general, it is better to control it via `alphabet` in `stretegies.text` (https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.text)

which is used here - https://github.com/Zac-HD/hypothesis-jsonschema/blob/master/src/hypothesis_jsonschema/_from_schema.py#L318

**Comment by MissiaL** [comment]
Thanks for answer! 
Maybe you need to add this example to README

**Comment by Stranger6667** [comment]
Sure, will add it as a part of a PR for #313 (hopefully this week)
