### ISSUE TITLE
Validate error for nullable properties

### ISSUE THREAD

**Issue by gurkalov** [kiwicom/schemathesis#335]
Hello, I make location_id property as nullable, but if in reponse of my service it property equal null, I have this error:

```
GET: /api/v1/users/{id} 
The received response does not conform to the defined schema!

Details: 

None is not of type 'integer'

Failed validating 'type' in schema['properties']['location_id']:
    {'example': 1, 'format': 'int64', 'nullable': True, 'type': 'integer'}

On instance['location_id']:
    None

Check           : response_schema_conformance
Path parameters : {'id': 1}

```

**Comment by Stranger6667** [comment]
Hello @gurkalov !

Thank you for bringing this :) I will check it

**Comment by Stranger6667** [comment]
It seems we don't convert OpenAPI 3.0 `nullable` attribute to one, supported by `jsonschema`.

**Comment by Stranger6667** [comment]
Should be fixed in `0.20.4` - https://pypi.org/project/schemathesis/0.20.4/

Feel free to reopen the issue if it doesn't fix the problem

**Comment by gurkalov** [comment]
@Stranger6667, thanks! It's great news! I will wait for it!

**Comment by Stranger6667** [comment]
> I will wait for it!

Not sure what do you mean, but Just in case - the new release is already on PyPI :)
