### ISSUE TITLE
Allowing RequestBodies for GET Requests

### ISSUE THREAD

**Issue by charliehohenstein30** [kiwicom/schemathesis#383]
Hi,

Is there any plan for the schemathesis library to allow for Request Bodies in GET requests?  I know this is against the specifications of OpenApi, but many Get requests may require request bodies (e.g. ElasticSearch).

Really enjoy this library! I think it would be very beneficial to have this option.

Thank you!

**Comment by Stranger6667** [comment]
Hej @charliehohenstein30 ! Thank you for the feedback :) I am glad to hear that this library is helpful for you :)

Some time ago we explicitly forbid this behavior, but I think this check can be explicitly opt-out because of existing practical cases where it is used. I'll work on it :)

**Comment by Stranger6667** [comment]
It will also require disabling schema verification (it is verified via `jsonschema` by default)

**Comment by Stranger6667** [comment]
At the moment that branch with body check is triggered only when schema validation is disabled (or with manually calling some internals), which, I think, should be enough - the user disables validation already, there shouldn't be any more steps to disable some more checks. In other words, removing this block and removing the corresponding test should be enough to make Schemathesis work for this case :)

**Comment by Stranger6667** [comment]
Ah no, I am wrong about this:
> that branch with body check is triggered only when schema validation is disabled

Will check it in more details and share it

**Comment by charliehohenstein30** [comment]
@Stranger6667 I appreciate the fast response, thank you for looking into it!

**Comment by charliehohenstein30** [comment]
I've tried to use this new feature in the following way:

schema = schemathesis.from_path(path_to_spec_file, validate_schema=False)

# start pytest
@schema.parametrize()
@settings(max_examples=1, deadline=20000)
def test_all_endpoints(case):

... asserts


However, I still receive 'Failed: Invalid schema for endpoint' when the endpoint with a RequestBody in a GET request is tested.

Am I implementing this incorrectly?

**Comment by charliehohenstein30** [comment]
This is the endpoint I am trying to test with this format

`/endpoint:
    get:
      parameters:
        - $ref: "#/components/parameters/UserIdHeader"
        - $ref: "#/components/parameters/ApiKey"
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                id:
                  type: integer
                  example: 10
                name:
                  type: string
                  example: 'Charlie'
              
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlanBenefits"
        "401":
          description: "Unauthorized"
        "500":
          description: Something went wrong`

**Comment by Stranger6667** [comment]
Sorry, I completely overlooked a bug in `BaseSchema.parametrize`. I will fix it in a few minutes.
Thank you for the detailed report :)

**Comment by Stranger6667** [comment]
So, there are few more issues with this method - I'll fix them asap and will release a new version

**Comment by Stranger6667** [comment]
The fixes released in `0.24.3` - https://pypi.org/project/schemathesis/0.24.3/

**Comment by charliehohenstein30** [comment]
@Stranger6667 This fixed worked! Thank you so much for the fast response and effort. Really appreciate it.

**Comment by Stranger6667** [comment]
Great to hear it! :) Let us know if we can do anything else :)
