### ISSUE TITLE
ERROR: schemathesis 0.25.0 has requirement werkzeug<0.17.0,>=0.16.0, but you'll have werkzeug 1.0.0 which is incompatible

### ISSUE THREAD

**Issue by 0anton** [kiwicom/schemathesis#433]
Dear colleagues,

While trying to install schemathesis from pip I've got an error:

`ERROR: schemathesis 0.25.0 has requirement werkzeug<0.17.0,>=0.16.0, but you'll have werkzeug 1.0.0 which is incompatible.
`

Apparently werkzeug 1.0.0 comes with a recent version of flask.

This means that schemathesis is unusable with the recent flask toolset?

Is it possible to relax this requirement?

I found this requirement definition:
https://github.com/kiwicom/schemathesis/blob/master/pyproject.toml
werkzeug = "^0.16.0"

Are there any specific reasons to keep it?

Anton

**Comment by Stranger6667** [comment]
Hello @0anton ,
Thank you for reporting this. We can relax the requirements, sure, I'll take a look

**Comment by Stranger6667** [comment]
Please, take a look at `0.25.1` - https://pypi.org/project/schemathesis/0.25.1/
It was released a few minutes ago and should be compatible with the new version of `werkzeug`

**Comment by 0anton** [comment]
Fantastic, Dmitry! That a fast response! Thank you very much for relaxing requirement!
