### ISSUE TITLE
Can't handle recursive json schema (openapi spec 3.0)

### ISSUE THREAD

**Issue by jeremyschiemann** [kiwicom/schemathesis#435]
Hello,

Schemathesis isn't able to resolve a recursive json schema (openapi spec 3.0), it will raise a recursion error. 
![image](https://user-images.githubusercontent.com/24566692/76391402-c2dcee80-636f-11ea-8496-ba71d53216f2.png)

A quick and dirty fix is to limit the max recursion depth in the resolve() function in schema.py like so 

```
    def resolve(self, item: Union[Dict[str, Any], List], recursion_level=0) -> Union[Dict[str, Any], List]:
        """Recursively resolve all references in the given object."""
        if recursion_level > 10:
            return item
        if isinstance(item, dict):
            item = self.prepare(item)
            if "$ref" in item:
                with self.resolver.resolving(item["$ref"]) as resolved:
                    return self.resolve(resolved, recursion_level+1)
            for key, sub_item in item.items():
                item[key] = self.resolve(sub_item, recursion_level)
        elif isinstance(item, list):
            for idx, sub_item in enumerate(item):
                item[idx] = self.resolve(sub_item, recursion_level)
        return item
```

Im not sure what would be the correct approach for this problem tho :)

Python 3.8.1
Schemathesis 0.25.1

**Comment by 0anton** [comment]
+1
Schemathesis breaks for us with the recursive schema too.

**Comment by jeremyschiemann** [comment]
I reduced the openapi.json to only contain the recursive part, for better understanding and fixing this problem

[reduced_spec.txt](https://github.com/kiwicom/schemathesis/files/4323097/reduced_spec.txt)

**Comment by Stranger6667** [comment]
Hello folks!
Thanks for reporting. This kind of schemas is not supported at the moment in Schemathesis indeed, as well as in `hypothesis-jsonschema`. I'll take a look at the issue next week, probably limiting the recursion depth should work

**Comment by Stranger6667** [comment]
The change in #441 should be sufficient for most of the cases, however, I expect that data generation will be quite slow. Let me know if the new version (`0.26.1`) works for you and feel free to re-open this issue

**Comment by Stranger6667** [comment]
Hi @mimkorn could you, please, share the schema with me? privately / publicly, anonymized, if it would work for you.
It would be beneficial to everybody if we could support more recursion cases without having to go with large reworks on the `hypothesis-jsonschema` side.

**Comment by mimkorn** [comment]
Hi @Stranger6667 , thanks for reaching out. I'll strip it down of details to get to the minimum if that's okay. If not, let's exchange some private comms channel. 

The following is a separate externally referenced JSON Schema file. In it, you can see "Fractal" model. We have some OAS which references this Fractal model. And as you can see, Fractal is self-referential via branch of a branch type that is Fractal. Self-referencing can also happen via an array. Same problem, just multiplied.

```json
{
  "definitions": {
    "Fractal": {
      "additionalProperties": {
        "$ref": "#/definitions/Branch"
      },
      "type": "object"
    },
    "Branch": {
      "oneOf": [
        {
          "$ref": "#/definitions/BranchType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BranchType"
          },
          "minItems": 1
        }
      ]
    },
    "BranchType": {
      "oneOf": [
        {
          "$ref": "#/definitions/Fractal"
        }
      ]
    }
  }
}
```

There's obviously much more to the schema, but the part where self-referencing happens is here.

**Comment by Stranger6667** [comment]
Thanks! I guess the issue is that we don't support recursion limiting through the "array" schemas. Let me confirm it and I'll create a new issue in the next few days

**Comment by mimkorn** [comment]
Hi, have you confirmed it and created a followup issue as mentioned? If so, could you link it here please so we can track if you've made any progress on it?
