### ISSUE TITLE
Inconsistent CLI opt show error/errors traceback help message

### ISSUE THREAD

**Issue by martinsirbe** [kiwicom/schemathesis#436]
The following output after running Schemathesis refers to use `--show-error-tracebacks` CLI opt.
```
suite_1  | ==================================== ERRORS ====================================
suite_1  | ______________________________ POST: /magic _______________________________
suite_1  | json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 129)
suite_1  | 
suite_1  | Add this option to your command line parameters to see full tracebacks: --show-error-tracebacks
```
https://github.com/kiwicom/schemathesis/commit/8804716d43549df0d5af0bca0c465e45c62e88d6#diff-2d6de91af2543cb0f0a51cf189ee5807R278

When I use this CLI opt, I get the following error message:
```
suite_1  | Error: no such option: --show-error-tracebacks
```

However based on the code, the CLI opt should be `--show-errors-tracebacks`
https://github.com/kiwicom/schemathesis/commit/8804716d43549df0d5af0bca0c465e45c62e88d6#diff-107869ea536a8ca2f75bdfec81685ddeR102

**Comment by Stranger6667** [comment]
Hello @martinsirbe !
Thank you for reporting this! It should be fixed in #438. Sorry for my slow response.
Regards
