### ISSUE TITLE
Pytest warning

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/schemathesis#451]
With the recent pytest version (5.4.1) there is a warning now:

```src/schemathesis/extra/pytest_plugin.py:46: PytestDeprecationWarning: direct construction of SchemathesisFunction has been deprecated, please use SchemathesisFunction.from_parent```

I think it should be easy to resolve

**Comment by 0anton** [comment]
+1
I am getting this also. It produce some noise in the test output. I'd appreciate if it is resolved.

**Comment by Stranger6667** [comment]
The fix is released in `1.0.2` https://pypi.org/project/schemathesis/1.0.2/

**Comment by Stranger6667** [comment]
There is one place, where I forgot to put a fix. I'll add it and will make a release today

**Comment by 0anton** [comment]
Resolved in 1.0.5!
