### ISSUE TITLE
Incorrectly handled description in paths

### ISSUE THREAD

**Issue by stepanbokoc** [kiwicom/schemathesis#457]
Hi,

In this example
```
openapi: "3.0.3"
paths:
  /:
    description: Description for all methods under path <------ This causes problem
    get:
      responses:
        '200':
         description: root response
```

if I try to use this schema and run tests it fails with error
```
/lib/python3.7/site-packages/schemathesis/schemas.py:212: in get_all_endpoints
    or should_skip_by_tag(definition.get("tags"), self.tag)
E   AttributeError: 'str' object has no attribute 'get'
```

It's because schemathesis tries to read data for each node under path (`/:` in this example) and fails because description is string and not object

Not everything under `path` is method ([Specification](https://swagger.io/docs/specification/paths-and-operations/)), there can be also description and summary. 
Only specified methods should be used (`get, post, put, patch, delete, head, options, and trace`)

**Comment by Stranger6667** [comment]
Hi! Thank you for your report!
There was a similar issue reported yesterday (#448) and my fix wasn't sufficient. I will re-check the spec and fix it properly

**Comment by Stranger6667** [comment]
Ok, according to the specs (and relevant JSON schemas, that are used for validation in Schemathesis) these are valid keys, that contain operations.

**Swagger**: "get", "put", "post", "delete", "options", "head", "patch"
**OpenAPI**: "get", "put", "post", "delete", "options", "head", "patch", "trace"

I'll submit a PR soon

**Comment by Stranger6667** [comment]
The fix is released in `1.0.2` https://pypi.org/project/schemathesis/1.0.2/

Feel free to reopen this issue if it won't work for your case :)

**Comment by stepanbokoc** [comment]
Works perfectly, thank you

**Comment by Stranger6667** [comment]
You are very welcome :)
