### ISSUE TITLE
content_type_conformance check not working for openapi 3

### ISSUE THREAD

**Issue by jeremyschiemann** [kiwicom/schemathesis#461]
Hi, 
the check `content_type_conformance` (in checks.py) is looking for the `produces` property, which is [openapi 2](https://swagger.io/docs/specification/2-0/mime-types/). In [openapi 3](https://swagger.io/docs/specification/media-types/) however this has moved to the individual response codes. 

This should be easily fixable by reading the response code and then adjust the json path in said check.

I also discovered that schemathesis (unintentionally) ignores the media types in it's requests for openapi 3. Which is probably the same problem.

schemathesis 1.0.2

**Comment by Stranger6667** [comment]
Hi @jeremyschiemann,
Oh, it is a nice discovery, I'll check & fix both cases, thank you :)

**Comment by Stranger6667** [comment]
Also, the current check implementation for OAS2 gives precedence to the global `produces`, however, operation-level `produces` should override the global one. I'll fix it too

**Comment by Stranger6667** [comment]
The fix is released in `1.0.3`
https://pypi.org/project/schemathesis/1.0.3/
