### ISSUE TITLE
Support or ignore extended formats

### ISSUE THREAD

**Issue by InfoSec812** [kiwicom/schemathesis#481]
I have an API Spec which has a field defined as follows:

```
id:
  type: string
  format: uuid
```

When I try to use schemathesis with this field, I get an error about a unsupported format. While I think supporting UUID would not be terribly difficult, I am wondering how deep the support should go... Perhaps in the future, someone wants a format of `currency` or `routing-id` or `asn`... Perhaps the right answer when the application encounters an unknown format is to use the example in the Spec?

**Comment by Stranger6667** [comment]
Hi! 
I think that this case is mentioned by the spec [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types)

> Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified.

Schemathesis relies on the behavior of `hypothesis-jsonschema` that ignores unknown formats starting from version `0.9.8` ([commit](https://github.com/Zac-HD/hypothesis-jsonschema/commit/90d2b34422d4ca8e67fd20f4423089cfeaa74cdd))

What version of `schemathesis` / `hypothesis-jsonschema` are you using? Also, could you, please, provide the error output? We have a couple of tests for that, but maybe we missed something

Btw, string formats can be extended. Please, take a look here - https://github.com/kiwicom/schemathesis#custom-string-strategies

For `uuid` of version 4 it should be something like this in case you use Schemathesis in Python tests:

```
from hypothesis import strategies

from schemathesis import register_string_format

register_string_format("uuid", strategies.uuids().map(str))
```

For CLI it will require using of `pre-run` hook:

```
schemathesis --pre-run importable.path.to.module run ...
```

Hope that it helps

**Comment by Zac-HD** [comment]
I'm also keen to move the `register_format` functionality upstream, see https://github.com/Zac-HD/hypothesis-jsonschema/issues/29 :smile:

**Comment by Stranger6667** [comment]
Hi @Zac-HD !

Sorry, I completely forgot about that opened issue :) Thank you for reminding :) I'll reply in that issue

**Comment by Stranger6667** [comment]
Closing this, since this was supported at the moment when this issue was created + as #685 is merged we don't use `hypothesis-jsonschema` private API for custom formats anymore and the high-level API in Schemathesis stays the same
