### ISSUE TITLE
Support for ASGI apps

### ISSUE THREAD

**Issue by HacKanCuBa** [kiwicom/schemathesis#510]
It would be nice to support ASGI apps (such as [FastAPI](https://fastapi.tiangolo.com)) so as to use them like it can currently be done with WSGI apps: `schemathesis run --app=importable.path:app ...`

**Comment by HacKanCuBa** [comment]
I think I could come up with something, allow me a few hours today. I saw the `from_wsgi` function and would try to replicate it using [starlette](https://www.starlette.io) test client, and then me could expand/improve from there.

**Comment by HacKanCuBa** [comment]
Well, I managed to load the app and the schema but now I need to change the runners. I would need several more days so I don't think I'm gonna be able to pull it so fast.
Anyway, I'm uploading what I've got in case someone wants to continue with this.

**Comment by mlaradji** [comment]
This project `https://github.com/abersheeran/a2wsgi` lets you convert an ASGI app to a WSGI app (and vice versa), allowing one to use the WSGI feature of `schemathesis`.  Note that it's a new project and I have only tested it minimally.

**Comment by Stranger6667** [comment]
Implemented in #630

**Comment by fbidu** [comment]
Hello all! 

I just wrote a simple integration with OpenAPI but I did it from a Python code instead of from the cli. I load the schema on this way:

```python
schema = schemathesis.from_dict(main.app.openapi())
```

And then performed the calls using a `TestClient` object in the `session` argument.

I wonder if this is the recommended way of doing this sort of integration and if @Stranger6667's PR will ease the process

all the best

**Comment by Stranger6667** [comment]
Hi @fbidu !

> And then performed the calls using a TestClient object in the session argument.

It is precisely what `Case.call_asgi` does :)

However, It depends on your test suite setup - if your app is already available during import time, then you could pass it to the `from_dict` function as an `app` argument. In this case, you won't need to pass it to the `case.call_asgi` method. So, it might even look like this:

```
schema = schemathesis.from_dict(main.app.openapi(), app=main.app)

@schema.parametrize()
def test_api(case):
    response = case.call_asgi()
    case.validate_response(response)
```

I'd say that the example above could serve as an example of how ASGI could work with minimal setup :) 

Let me know if I can provide more info.

**Comment by Stranger6667** [comment]
But in general, it is perfectly fine to use a separate client, especially if you need to reuse it in multiple tests
