### ISSUE TITLE
should not take base path from schema['servers'] url, if base_url is given in runner.prepare

### ISSUE THREAD

**Issue by arvindjangra1996** [kiwicom/schemathesis#511]
Hi, thanks for the great library.
if my openapi schema contains server url as `https://abc.xyz.com/a1`
But during testing, i also want the base_url to be my testing url. say `https://testing.xyz.com/t1`

I want `https://testing.xyz.com/t1/fetch` to run for my `/fetch` path, not `https://testing.xyz.com/t1/a1/fetch`

**Comment by Stranger6667** [comment]
@arvindjangra1996 thanks :)

Indeed, this part is broken. I am working on a fix

**Comment by Stranger6667** [comment]
Oh, it seems like we need to rework our base_url handling. The change will be backward-incompatible, it will take some more time

**Comment by arvindjangra1996** [comment]
okay. :)

**Comment by arvindjangra1996** [comment]
Hey, is this issue handled in new release ?

**Comment by Stranger6667** [comment]
Hi, I forgot to change the milestone, that PR will be finalized and merged in a few days together with #581 . It will be 2.0 release

**Comment by arvindjangra1996** [comment]
okay. Thanks :)
