### ISSUE TITLE
why is pytest-subtests 0.2.1 required?

### ISSUE THREAD

**Issue by jeremyschiemann** [kiwicom/schemathesis#537]
Hi, 

why is specifically pytest-subtest 0.2.1 required for installing schemathesis?
Installing schemathesis with pytest-subtests 0.3.0 will uninstall it and install 0.2.1

Kind Regards

**Comment by Stranger6667** [comment]
Hi!
I think that there is no specific reason and we can relax our requirements. I'll test the new version of `pytest-subtest`
