### ISSUE TITLE
Validate error for nullable properties since v1.3.0

### ISSUE THREAD

**Issue by grigi** [kiwicom/schemathesis#542]
Hi, I have `schemathesis==1.3.3` and I have the same issue as #335:
```
Details: 

None is not of type 'string'

Failed validating 'type' in schema['items']['properties']['family_name']:
    {'maxLength': 50,
     'nullable': True,
     'title': 'Family Name',
     'type': 'string'}

On instance[0]['family_name']:
    None
```

I tested older versions, This is working in v1.2.0, but regressed since v1.3.0

**Comment by Stranger6667** [comment]
Hi!
Thank you for reporting this :) Where does this error happen? Could you, please, share a traceback? At least partially. And you are using Open API 3.0.x, right?

**Comment by grigi** [comment]
I'm using Pydantic, which tells me it is openapi 3.0.2
Why? Is this functionality removed since 3?

I'm running from the CLI:
```
schemathesis run http://127.0.0.1:8000/openapi.json -c all
```

And the error I get is printed on the output. So no traceback, unfortunately.
The full error is:
```
1. The received response does not conform to the defined schema!

Details:                                                                                                                                                                                                                                                                                 

None is not of type 'string'                                                                                                                                                                                                                                                             

Failed validating 'type' in schema['items']['properties']['name']:                                                                                                                                                                                                                       
    {'maxLength': 50, 'nullable': True, 'title': 'Name', 'type': 'string'}                                                                                                                                                                                                               

On instance[0]['name']:                                                                                                                                                                                                                                                                  
    None                                                                                                                                                                                                                                                                                 

Check           : response_schema_conformance

Run this Python code to reproduce this failure: 

    requests.get('http://127.0.0.1:8000/users')                                                                                                                                                                                                                                          

Or add this option to your command line parameters: --hypothesis-seed=53641920147263667326410162485018230946                                                                                                                                                                             
```

The relevant schema of the attribute is:
```
      "User": {
        "title": "User",
        "required": [
          "id",
          "username",
          "created_at",
          "modified_at",
          "full_name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "title": "Id",
            "maximum": 2147483647,
            "minimum": 1,
            "type": "integer"
          },
          "username": {
            "title": "Username",
            "maxLength": 20,
            "type": "string",
            "description": "This is a username"
          },
          "name": {
            "title": "Name",
            "maxLength": 50,
            "type": "string",
            "nullable": true
          },
          "family_name": {
            "title": "Family Name",
            "maxLength": 50,
            "type": "string",
            "nullable": true
          },
          "category": {
            "title": "Category",
            "maxLength": 30,
            "type": "string"
          },
          "created_at": {
            "title": "Created At",
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
          "modified_at": {
            "title": "Modified At",
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
          "full_name": {
            "title": "Full Name",
            "type": "string",
            "description": "Returns the best name"
          }
        },
        "additionalProperties": false,
        "description": "The User model"
      },
```

**Comment by Stranger6667** [comment]
> Why? Is this functionality removed since 3?
Just to narrow down the changes we added recently, there were some related to the `response_schema_conformance` check in attempt to fix another issue (#435). It seems to me that I'd revert those changes and will work on a proper fix.

Thank you for providing the info, it will definitely help us to create a regression test case

**Comment by grigi** [comment]
A pleasure. I was mainly wanting to verify that my auto-generated schemas was sane for Tortoise ORM.

This tool already helped me find two bugs. :+1:
(The one was trivial, the one was handling NULL characters in strings... Most SQL db's are written in C, and uses null terminated strings...)

**Comment by Stranger6667** [comment]
Glad to hear that the library helped you :)

> the one was handling NULL characters in strings... Most SQL db's are written in C, and uses null terminated strings...

I believe it is one of the most frequent issues we found in our apps :) quite rare to see on production, but still I saw it multiple times :)

**Comment by grigi** [comment]
I NULL chars working for SQLite and MySQL. But PostgreSQL will never allow it. So I am going to raise an encoding error for that. :man_shrugging: 

Since hypothesis isn't async compatible, I decided to see if this works as a reasonable fuzzer proxy, and it seems pretty good so far. I'll likely include it into our CI :-D

**Comment by Stranger6667** [comment]
> Since hypothesis isn't async compatible, I decided to see if this works as a reasonable fuzzer proxy, and it seems pretty good so far. I'll likely include it into our CI :-D

Sounds interesting :) You mean Schemathesis, right?

Anyway, I'd be happy to know if there are any features we can do to improve your workflow :)

**Comment by Stranger6667** [comment]
@grigi 

Instead of reverting those changes, I applied a fix which is released in [1.3.4](https://pypi.org/project/schemathesis/1.3.4/).

Let me know if it fixes your case

**Comment by grigi** [comment]
No, I meant I wanted to directly integrate with hypothesis for tests, but it required a LOT of work to make it compatible with async call, so I thought since I have this jsonschema generation already, I could just do basic fuzz testing via HTTP with an external tool. Which is Schemathesis :grin: 

And thank you for fixing this so fast! I can confirm that 1.3.4 fixes the issue for me :+1:

**Comment by Stranger6667** [comment]
> And thank you for fixing this so fast! I can confirm that 1.3.4 fixes the issue for me +1

Great! You are welcome :)

> so I thought since I have this jsonschema generation already, I could just do basic fuzz testing via HTTP with an external tool.

Aha, I understand now :) Cool! Let me know if I can do anything else from the Schemathesis side to  improve your workflow :)

**Comment by stepanbokoc** [comment]
Hi, I think this issue will still occur (in v1.4.0) when schema is referenced. Correct me if I'm wrong but I think that 
`case.endpoint.schema._get_response_schema(definition, case.endpoint.definition.scope)` call does not return fully resolved schema and thus `to_json_schema` does not replace all occurrences of `nullable: true` to equivalent in json schema

In my schema I have path like this 
```
get:
  description: List of all child companies
  tags:
    - Company
  responses:
    200:
      description: Child company list. Returns all child companies
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../openapi.yml#/components/schemas/Company"
```
and inside the schema
```
  updated_at:
      type: string
      format: 'date-time'
      nullable: true
```
and it ends with exact error as this issue mentions

**Comment by Stranger6667** [comment]
@stepanbokoc I assume you are right! It seems like we need to use a custom validator / resolver to completely solve this issue! Thank you for bringing this up

**Comment by stepanbokoc** [comment]
Yes, I'm currently using custom `response_schema_conformance` function to make it work for my case 
(The comment I made above is with standard `response_schema_conformance` function)

**Comment by Stranger6667** [comment]
I prepared a draft that will fix this issue and another one as well - nested reference inside response schemas. Now only one level is resolved, but actually there could be arbitrarily many levels. #561
