### ISSUE TITLE
KeyError: schema when using content to describe request parameters

### ISSUE THREAD

**Issue by shabbyrobe** [kiwicom/schemathesis#594]
When I describe my parameters using `content` as outlined in the [OpenAPI docs](https://swagger.io/docs/specification/describing-parameters/#schema-vs-content), I get a KeyError as schemathesis appears to only support `schema`:

> content is used in complex serialization scenarios that are not covered by style and explode. For example, if you need to send a JSON string in the query string like so:
>
>    filter={"type":"t-shirt","color":"blue"}

The spec for the above looks like so:

```
    parameters:
      - in: query
        name: filter
    	
        # Wrap 'schema' into 'content.<media-type>'
        content:
          application/json:  # <---- media type indicates how to serialize / deserialize the parameter content
            schema:
              type: object
              properties:
                type:
                  type: string
                color:
                  type: string
```

This is exactly what appears in the API I'm attempting to introduce a spec for. If I go through and delete all the `content` parameters, schemathesis parses the spec without incident.

Here's what I believe to be the relevant chunk of the resulting exception:

```
  File "/Users/bwilliams7/work/av-api-test/venv/lib/python3.6/site-packages/schemathesis/specs/openapi/schemas.py", line 190, in add_parameter
    container["properties"][name] = self.parameter_to_json_schema(parameter)
  File "/Users/bwilliams7/work/av-api-test/venv/lib/python3.6/site-packages/schemathesis/specs/openapi/schemas.py", line 300, in parameter_to_json_schema
    return super().parameter_to_json_schema(data["schema"])
KeyError: 'schema'
```

**Comment by Stranger6667** [comment]
Hi @shabbyrobe !

Unfortunately, we don't support it :( I'll add it to our backlog. Thank you for reporting this

**Comment by Stranger6667** [comment]
Hi there!

I added support for `application/json` serialization in `1.7.0`. Let me know if it works for you

**Comment by shabbyrobe** [comment]
Thanks so much @Stranger6667, this is a huge help! I will take it for a spin this week.
