### ISSUE TITLE
--header does not support : in header value

### ISSUE THREAD

**Issue by thim81** [kiwicom/schemathesis#596]
Hi,

I'm using the CLI docker solution; with the following command to run the testing.

`docker run kiwicom/schemathesis:stable run -w 8 --base-url=https://localhost:8000 --header=X-ApiKey:123BDKxY=:123WP6d5Bo3tlw= openapi.json --junit-xml=junit.xml`

The header value is a combination of 2 encoded strings, which is divided by the ":".
It seems that is not supported, since I got the following error:

`Error: Invalid value for '--header' / '-H': Should be in KEY:VALUE format. Got: X-ApiKey:123BDKxY=:123WP6d5Bo3tlw=`

Is there a way that I can overcome this error, by wrapping the value in quotes? Or another way around this error?

**Comment by Stranger6667** [comment]
Hi @thim81 !

Probably I overlooked this! And I don't think that there is a decent workaround to overcome this error. However, let me look into the code and I believe we can add support for it

**Comment by Stranger6667** [comment]
The fix is released in [1.6.3](https://pypi.org/project/schemathesis/1.6.3/)

Please, let me know if it fixes your case

**Comment by thim81** [comment]
Hi Dmitry,

I can confirm the header now works.
Thanks for the quick follow-up.
