### ISSUE TITLE
Overly verbose error output

### ISSUE THREAD

**Issue by presto21** [kiwicom/schemathesis#598]
When an error was encountered, the entire schema is printed as part of the error message. This makes it makes difficult understand the actual error. I wanted to find a way to make the error output more concise. This lead to the idea of creating a new OutputStyleHandler that:
-  Minimize the overly verbose output in the new output style handler
- Give the user more flexibility about what they want in the output

Example of overly verbose output:
![codeError](https://user-images.githubusercontent.com/60228581/83024128-86767180-9ff3-11ea-94f6-ae741c3d8850.jpeg)
 
I have implemented some code that I want to contribute. 
- added a new CLI option to invoke the new OutputStyleHandler
- made changes to the run, prepared_runner, and execute functions to incorporate the new options
- added a new output format file in the 'output' directory. 

Feel free to ask any questions or concerns. I wanted to share my idea and the reason before I created a PR.

**Comment by Stranger6667** [comment]
Hi @presto21 !

Thank you for your contribution, I appreciate it :)

Indeed, it is too verbose. I decided to rely on the default `jsonschema` output for simplicity and didn't actually look for alternative representation and I am happy that you brought this up :)

Some time ago I prototyped some `--verbosity` option but didn't finish it. Probably it could be either updating the existing handlers or creating a new one, depending on what is simpler & more flexible. So I'd be happy to check out your implementation :) From what I see in your comment everything seems fine :)

The most interesting part for me is how the output will look like with different option values :) Could you, please, share how it might look like with the new handler? e.g. in a PR
