### ISSUE TITLE
Limit generated test cases when using CLI

### ISSUE THREAD

**Issue by idoqo** [kiwicom/schemathesis#653]
Hi, went through the docs and it provides steps to modify the number of generated test cases (instead of the default 100) using code [here](https://github.com/kiwicom/schemathesis#in-code). I was wondering if it's possible to do that when using the CLI also since my API isn't in python anyway.

**Comment by Stranger6667** [comment]
Hi! Yes, you could use ‘--hypothesis-max-examples’ command line option

**Comment by idoqo** [comment]
Oh thanks a lot. Should have paid more attention to the help info.

**Comment by Stranger6667** [comment]
You are welcome! Let me know if I can provide more info :) We also have gitter - https://gitter.im/kiwicom/schemathesis
