### ISSUE TITLE
Error during authorization via token

### ISSUE THREAD

**Issue by inghvar** [kiwicom/schemathesis#68]
When my endpoint requires authorization through the token that is sent via header, I get the following error:
_requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization_
Does the program work for "closed" endpoints?

**Comment by Stranger6667** [comment]
Hello @inghvar !

Currently, the authorization should be done manually, for example:

```
from requests.auth import HTTPBasicAuth

@schema.parametrize()
def test_no_server_errors(case):
    response = requests.request(
        case.method,
        f"{BASE_URL}{case.formatted_path}",
        headers=case.headers,
        params=case.query,
        json=case.body,
        auth=HTTPBasicAuth("user", "pass")
    )
    assert response.status_code < 500
```

An example with jwt auth and a separate fixture

```
import pytest

@pytest.fixture
def session():
    with requests.Session() as s:
        auth_response = s.post(f"{BASE_URL}/login")
        token = auth_response.json()["access_token"]
        s.headers["Authorization"] = f"Bearer {token}"
        yield s

@schema.parametrize()
def test_no_server_errors(case, session):
    response = session.request(
        case.method,
        f"{BASE_URL}{case.formatted_path}",
        headers=case.headers,
        params=case.query,
        json=case.body,
    )
    assert response.status_code < 500
```

We plan to add some helpers in the future

**Comment by Stranger6667** [comment]
There is a couple of updates.
We added options for authorization in CLI:
```
# Basic auth
schemathesis run --auth your:password http://example.com/schema.json
# Digest auth
schemathesis run --auth your:password -A digest http://example.com/schema.json
# Custom authorization header
schemathesis run -H Authorization:\ Token YOUR_TOKEN http://example.com/schema.json
```
In the code it is slightly simplified now:

```
from requests.auth import HTTPBasicAuth

@schema.parametrize()
def test_no_server_errors(case):
    response = case.call(auth=HTTPBasicAuth("user", "pass"))
    assert response.status_code < 500
```

It is possible to pass custom kwargs to `case.call` and they will go directly to `requests.request`.

That's all we have for now and we'll be happy to consider any suggestions that will improve Schemathesis :) Feel free to open a new issue for that

**Comment by Stranger6667** [comment]
Hm, now I am re-reading the error you submitted and realize that there could be an issue.
Hypothesis will generate random data that could be not valid for `requests` headers validation and actually hard to send via tools like `requests` or `curl`, but I am wondering if they still can be sent and therefore processed by the backend. Probably we can tune it somehow but by default generate valid headers only
