### ISSUE TITLE
Problem with endpoint with file as multipart/form-data

### ISSUE THREAD

**Issue by jeremyschiemann** [kiwicom/schemathesis#694]
Hi,

I have an endpoints which accepts a file as multipart/form-data correctly but I didn't manage to get Schemathesis to work with it. It has no implementation and yet and always replies with 200 using curl or the swagger ui. The Schemathesis tests are always giving me a code 400.

here is my schema [file_schema.json.txt](https://github.com/kiwicom/schemathesis/files/5041159/file_schema.json.txt)

my code looks roughly like this (Note: other Hypothesis phases besides 'explicit' also don't work)
```python
schema = schemathesis.loaders.from_asgi(app=app,
                                        schema_path="/openapi.json")

@schema.parametrize()
@settings(deadline=None, phases=[Phase.explicit])
def test_examples(case):
    """Check if the given examples are valid and return 200 code"""
    log_case(case)  # log case as curl command
    res = case.call_asgi()
    case.validate_response(res)
    assert res.status_code == 200
```

In another manual test, the endpoint works fine
```python
import pytest
from starlette.testclient import TestClient
from pathlib import Path
from app.main import app


@pytest.fixture(scope="module")
def test_app():
    client = TestClient(app)
    yield client

def test_analysis(test_app):
    dir = Path(__file__)
    filename = "sample_xml.xml"
    with open(dir.parent.joinpath(filename), 'r') as xml_file:
        response = test_app.post("/analysis?type=abc",
                                 files={"file": (filename, xml_file, "text/xml")})
        assert response.status_code == 200
        assert response.json() == {'status': 'accepted', 'id': 'UID-XXXXXX', 'error': None}
```
 
 Am I missing something?

I hope thats enough for you to help me :)

**Comment by Stranger6667** [comment]
Hi @jeremyschiemann 

From the schema point of view, the semantic meaning of that payload is not clear for Schemathesis - the `file` property has type `string` and format `binary` and Schemathesis generates various binary strings. There is no direct information that the backend expects XML payload for this field, we could guess it from the example, but it is a very imprecise approach.

Currently, Schemathesis doesn't support generating specific payload types except for form data and json. But it is supported by the spec - https://swagger.io/docs/specification/describing-request-body/multipart-requests/ see the "Specifying Content-Type" subsection:

```json
"requestBody": {
    "content": {
        "multipart/form-data": {
            "schema": {
                "required": ["file"],
                "type": "object",
                "properties": {
                    "file": {
                        "title": "File",
                        "type": "string",
                        "format": "binary",
                        "example": '<?xml version="1.0"?><test></test>',
                    }
                },
            },
            "encoding": {
                "file": {
                    "contentType": "text/xml"
                }
            }
        }
    },
    "required": True,
}
```

Taking the content type from there shouldn't be hard to implement (+ also there are headers in this object, etc), but generating a semantically valid payload is harder. We can start with pre-defined examples for common content types, but ideally, it would require proper hypothesis strategies that might require their complete implementation (for some cases we can use existing ones). 

It is definitely a good feature to implement, but I am not sure about the priorities - there are some parts in Schemathesis I wanted to implement before any major feature. However, I'd be happy to review contributions

**Comment by jeremyschiemann** [comment]
Thanks for the explanation, 
I'll see what I can do.

BTW: Is it possible to exclude an endpoint from testing?

**Comment by Stranger6667** [comment]
You are welcome!

> BTW: Is it possible to exclude an endpoint from testing?

Unfortunately, there is no direct way to do so, but you can use regular expressions as the `endpoint` argument value. For example to exclude all endpoints starting with `/users` using a negative lookahead:

```python

@schema.parametrize(endpoint="^(?!/users).*$")
def test_api(case):
    ...
```
