### ISSUE TITLE
How to add static path-parameter and quey param for each request

### ISSUE THREAD

**Issue by samuelguesnier** [kiwicom/schemathesis#698]
Hello and thank you so much for this library.

I'm trying to use it but I face an issue.
I have this endpoint: /subscriptions/{subscriptionUid}/devices

I'd like to fix  the {subscriptionUid} and the sessionToken value so I can have interesting tests with random bodies.

I did this:

```# org_schemathesis.py
from typing import List
                                                                               
import schemathesis
from schemathesis.models import Case
from hypothesis import strategies
 
 
@schemathesis.hooks.register
def before_add_examples(
        context: schemathesis.hooks.HookContext,
        examples: List[Case],
    ) -> None:
    examples.append(
        Case(endpoint=context.endpoint, path_parameters={'subscriptionUid': 1384},cookies={'JSESSIONID':'iO0X8vqvw2GVm5w_SsszKkCMDd_pkD2'}, query={'sessionToken': '4202488a890'})
        )
```

The program execute only one example with theses values, without body, then , the other example are executed with a randomized body but the subscriptionID , sessionToken and even cookie are randomized too. So I don't get revelant tests to me :/

Is it possible to add theses values for each examples ?

Thanks

**Comment by Stranger6667** [comment]
Hi @samuelguesnier 

Thank you! I appreciate that you like it :) 

I am sorry for not responding to you on gitter.

> Is it possible to add theses values for each examples ?

Yes, this hook, you used - `before_add_examples` only adds test cases for the Hypothesis's "explicit" testing stage, where all explicit examples from your schema are tested. If there is not enough static data to send, then Schemathesis will fill the gaps with randomized data, that fits the schema. But it seems like this hook is not what you want.

>  the other example are executed with a randomized body but the subscriptionID , sessionToken and even cookie are randomized too.

The most straightforward way to put static data into a test case would be to modify it directly inside your test:


```python

@schema.parametrize()
def test_api(case):
    case.path_parameters["subscriptionUid"] = 1384
    case.cookies["JSESSIONID"] = "iO0X8vqvw2GVm5w_SsszKkCMDd_pkD2"
    case.query["sessionToken"] = "202488a890"
    response = case.call()
    # test logic
```

However, this recipe is only for Python tests. For CLI, it might be more cumbersome (at least for now!). Here is an example, but in general, you could take a look at the "Customization" [section](https://schemathesis.readthedocs.io/en/stable/customization.html#common-hooks):

```python
@schemathesis.hooks.register
def before_generate_query(context, strategy):

    def set_token(query):
        query["sessionToken"] = "202488a890"

    return strategy.map(set_token)

# Similarly
# before_generate_path_parameters
# before_generate_cookies
```

So, you have to create 3 functions named `before_generate_query`, `before_generate_path_parameters`, `before_generate_cookies` and wrap them with `schemathesis.hooks.register` and then use the `--pre-run` CLI option. This approach is not the most efficient one, though, but probably it is not that important.

It would also be nice to have a hook that will accept a case instance, so you could modify it before it is sent to the application under test - I created #700, so it might become easier to change cases with static data in the future.

Let me know if I can provide more examples or any other support :)

Cheers

**Comment by samuelguesnier** [comment]
Thank you @Stranger6667 for your help and your time :) It is now working.

**Comment by Stranger6667** [comment]
@samuelguesnier I am glad to hear that :)
